/* ============================================================ */
/* x86_64-vex.h — VEX/EVEX instruction table for TCC           */
/*                                                              */
/* Included multiple times with different DEF_VEX_OP* macros.  */
/* Do NOT add include guards or #include directives.            */
/* ============================================================ */

/* ============================================================ */
/* Section 1: AVX Data Movement (mm=1: 0F)                      */
/* ============================================================ */

/* Load / reg-reg and store forms */
DEF_VEX_OP2(vmovaps, 1, 0, 0x28, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM)
ALT(DEF_VEX_OP2(vmovaps, 1, 0, 0x29, VEXF_MODRM, OPT_XYZMM, OPT_XYZMM | OPT_EA))

DEF_VEX_OP2(vmovapd, 1, 1, 0x28, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM)
ALT(DEF_VEX_OP2(vmovapd, 1, 1, 0x29, VEXF_MODRM, OPT_XYZMM, OPT_XYZMM | OPT_EA))

DEF_VEX_OP2(vmovups, 1, 0, 0x10, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM)
ALT(DEF_VEX_OP2(vmovups, 1, 0, 0x11, VEXF_MODRM, OPT_XYZMM, OPT_XYZMM | OPT_EA))

DEF_VEX_OP2(vmovupd, 1, 1, 0x10, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM)
ALT(DEF_VEX_OP2(vmovupd, 1, 1, 0x11, VEXF_MODRM, OPT_XYZMM, OPT_XYZMM | OPT_EA))

DEF_VEX_OP2(vmovdqa, 1, 1, 0x6f, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM)
ALT(DEF_VEX_OP2(vmovdqa, 1, 1, 0x7f, VEXF_MODRM, OPT_XYZMM, OPT_XYZMM | OPT_EA))

DEF_VEX_OP2(vmovdqu, 1, 2, 0x6f, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM)
ALT(DEF_VEX_OP2(vmovdqu, 1, 2, 0x7f, VEXF_MODRM, OPT_XYZMM, OPT_XYZMM | OPT_EA))

DEF_VEX_OP2(vmovss, 1, 2, 0x10, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM)
ALT(DEF_VEX_OP2(vmovss, 1, 2, 0x11, VEXF_MODRM, OPT_XYZMM, OPT_XYZMM | OPT_EA))

DEF_VEX_OP2(vmovsd, 1, 3, 0x10, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM)
ALT(DEF_VEX_OP2(vmovsd, 1, 3, 0x11, VEXF_MODRM, OPT_XYZMM, OPT_XYZMM | OPT_EA))

DEF_VEX_OP2(vmovshdup, 1, 2, 0x16, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM)
DEF_VEX_OP2(vmovsldup, 1, 2, 0x12, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM)
DEF_VEX_OP2(vmovddup,  1, 3, 0x12, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM)

DEF_VEX_OP2(vmovntps, 1, 0, 0x2b, VEXF_MODRM, OPT_XYZMM, OPT_EA)
DEF_VEX_OP2(vmovntpd, 1, 1, 0x2b, VEXF_MODRM, OPT_XYZMM, OPT_EA)
DEF_VEX_OP2(vmovntdq, 1, 1, 0xe7, VEXF_MODRM, OPT_XYZMM, OPT_EA)

DEF_VEX_OP2(vmovd, 1, 1, 0x6e, VEXF_MODRM, OPT_REG32 | OPT_EA, OPT_XYZMM)
ALT(DEF_VEX_OP2(vmovd, 1, 1, 0x7e, VEXF_MODRM, OPT_XYZMM, OPT_REG32 | OPT_EA))

DEF_VEX_OP2(vmovq, 1, 2, 0x7e, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM)
ALT(DEF_VEX_OP2(vmovq, 1, 1, 0xd6, VEXF_MODRM, OPT_XYZMM, OPT_XYZMM | OPT_EA))
ALT(DEF_VEX_OP2(vmovq, 1, 1, 0x6e, VEXF_MODRM | VEXF_W1, OPT_REG64 | OPT_EA, OPT_XYZMM))
ALT(DEF_VEX_OP2(vmovq, 1, 1, 0x7e, VEXF_MODRM | VEXF_W1, OPT_XYZMM, OPT_REG64 | OPT_EA))

DEF_VEX_OP2(vmovmskps, 1, 0, 0x50, VEXF_MODRM, OPT_XYZMM, OPT_REG32 | OPT_REG64)
DEF_VEX_OP2(vmovmskpd, 1, 1, 0x50, VEXF_MODRM, OPT_XYZMM, OPT_REG32 | OPT_REG64)

/* ============================================================ */
/* Section 2: AVX Arithmetic (3-operand: src2, src1, dst)       */
/* ============================================================ */

DEF_VEX_OP3(vaddps, 1, 0, 0x58, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vaddpd, 1, 1, 0x58, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vaddss, 1, 2, 0x58, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vaddsd, 1, 3, 0x58, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)

DEF_VEX_OP3(vsubps, 1, 0, 0x5c, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vsubpd, 1, 1, 0x5c, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vsubss, 1, 2, 0x5c, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vsubsd, 1, 3, 0x5c, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)

DEF_VEX_OP3(vmulps, 1, 0, 0x59, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vmulpd, 1, 1, 0x59, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vmulss, 1, 2, 0x59, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vmulsd, 1, 3, 0x59, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)

DEF_VEX_OP3(vdivps, 1, 0, 0x5e, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vdivpd, 1, 1, 0x5e, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vdivss, 1, 2, 0x5e, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vdivsd, 1, 3, 0x5e, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)

DEF_VEX_OP2(vsqrtps, 1, 0, 0x51, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM)
DEF_VEX_OP2(vsqrtpd, 1, 1, 0x51, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM)
DEF_VEX_OP3(vsqrtss, 1, 2, 0x51, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vsqrtsd, 1, 3, 0x51, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)

DEF_VEX_OP2(vrcpps,   1, 0, 0x53, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM)
DEF_VEX_OP3(vrcpss,   1, 2, 0x53, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP2(vrsqrtps, 1, 0, 0x52, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM)
DEF_VEX_OP3(vrsqrtss, 1, 2, 0x52, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)

DEF_VEX_OP3(vminps, 1, 0, 0x5d, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vminpd, 1, 1, 0x5d, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vminss, 1, 2, 0x5d, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vminsd, 1, 3, 0x5d, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)

DEF_VEX_OP3(vmaxps, 1, 0, 0x5f, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vmaxpd, 1, 1, 0x5f, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vmaxss, 1, 2, 0x5f, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vmaxsd, 1, 3, 0x5f, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)

DEF_VEX_OP3(vhaddps,   1, 3, 0x7c, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vhaddpd,   1, 1, 0x7c, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vhsubps,   1, 3, 0x7d, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vhsubpd,   1, 1, 0x7d, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vaddsubps, 1, 3, 0xd0, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vaddsubpd, 1, 1, 0xd0, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)

/* ============================================================ */
/* Section 3: AVX Logic                                         */
/* ============================================================ */

DEF_VEX_OP3(vandps,  1, 0, 0x54, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vandpd,  1, 1, 0x54, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vandnps, 1, 0, 0x55, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vandnpd, 1, 1, 0x55, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vorps,   1, 0, 0x56, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vorpd,   1, 1, 0x56, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vxorps,  1, 0, 0x57, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vxorpd,  1, 1, 0x57, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)

/* ============================================================ */
/* Section 4: AVX Comparison                                    */
/* ============================================================ */

DEF_VEX_OP4(vcmpps, 1, 0, 0xc2, VEXF_MODRM | VEXF_IMM8, OPT_IM8, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP4(vcmppd, 1, 1, 0xc2, VEXF_MODRM | VEXF_IMM8, OPT_IM8, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP4(vcmpss, 1, 2, 0xc2, VEXF_MODRM | VEXF_IMM8, OPT_IM8, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP4(vcmpsd, 1, 3, 0xc2, VEXF_MODRM | VEXF_IMM8, OPT_IM8, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)

DEF_VEX_OP2(vucomiss, 1, 0, 0x2e, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM)
DEF_VEX_OP2(vucomisd, 1, 1, 0x2e, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM)
DEF_VEX_OP2(vcomiss,  1, 0, 0x2f, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM)
DEF_VEX_OP2(vcomisd,  1, 1, 0x2f, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM)

/* ============================================================ */
/* Section 5: AVX Conversion                                    */
/* ============================================================ */

DEF_VEX_OP2(vcvtps2pd,  1, 0, 0x5a, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM)
DEF_VEX_OP2(vcvtpd2ps,  1, 1, 0x5a, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM)
DEF_VEX_OP2(vcvtps2dq,  1, 1, 0x5b, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM)
DEF_VEX_OP2(vcvtdq2ps,  1, 0, 0x5b, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM)
DEF_VEX_OP2(vcvtpd2dq,  1, 3, 0xe6, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM)
DEF_VEX_OP2(vcvtdq2pd,  1, 2, 0xe6, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM)
DEF_VEX_OP2(vcvttps2dq, 1, 2, 0x5b, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM)
DEF_VEX_OP2(vcvttpd2dq, 1, 1, 0xe6, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM)

DEF_VEX_OP3(vcvtss2sd,  1, 2, 0x5a, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vcvtsd2ss,  1, 3, 0x5a, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)

DEF_VEX_OP3(vcvtsi2ss,  1, 2, 0x2a, VEXF_MODRM, OPT_REG32 | OPT_EA, OPT_XYZMM, OPT_XYZMM)
ALT(DEF_VEX_OP3(vcvtsi2ss,  1, 2, 0x2a, VEXF_MODRM | VEXF_W1, OPT_REG64 | OPT_EA, OPT_XYZMM, OPT_XYZMM))
DEF_VEX_OP3(vcvtsi2sd,  1, 3, 0x2a, VEXF_MODRM, OPT_REG32 | OPT_EA, OPT_XYZMM, OPT_XYZMM)
ALT(DEF_VEX_OP3(vcvtsi2sd,  1, 3, 0x2a, VEXF_MODRM | VEXF_W1, OPT_REG64 | OPT_EA, OPT_XYZMM, OPT_XYZMM))

DEF_VEX_OP2(vcvtss2si,  1, 2, 0x2d, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_REG32)
ALT(DEF_VEX_OP2(vcvtss2si,  1, 2, 0x2d, VEXF_MODRM | VEXF_W1, OPT_XYZMM | OPT_EA, OPT_REG64))
DEF_VEX_OP2(vcvtsd2si,  1, 3, 0x2d, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_REG32)
ALT(DEF_VEX_OP2(vcvtsd2si,  1, 3, 0x2d, VEXF_MODRM | VEXF_W1, OPT_XYZMM | OPT_EA, OPT_REG64))

DEF_VEX_OP2(vcvttss2si, 1, 2, 0x2c, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_REG32)
ALT(DEF_VEX_OP2(vcvttss2si, 1, 2, 0x2c, VEXF_MODRM | VEXF_W1, OPT_XYZMM | OPT_EA, OPT_REG64))
DEF_VEX_OP2(vcvttsd2si, 1, 3, 0x2c, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_REG32)
ALT(DEF_VEX_OP2(vcvttsd2si, 1, 3, 0x2c, VEXF_MODRM | VEXF_W1, OPT_XYZMM | OPT_EA, OPT_REG64))

/* ============================================================ */
/* Section 6: AVX Shuffle / Permute / State                     */
/* ============================================================ */

DEF_VEX_OP4(vshufps, 1, 0, 0xc6, VEXF_MODRM | VEXF_IMM8, OPT_IM8, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP4(vshufpd, 1, 1, 0xc6, VEXF_MODRM | VEXF_IMM8, OPT_IM8, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)

DEF_VEX_OP3(vunpcklps, 1, 0, 0x14, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vunpckhps, 1, 0, 0x15, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vunpcklpd, 1, 1, 0x14, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vunpckhpd, 1, 1, 0x15, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)

DEF_VEX_OP3(vpermilps, 3, 1, 0x04, VEXF_MODRM | VEXF_IMM8, OPT_IM8, OPT_XYZMM | OPT_EA, OPT_XYZMM)
DEF_VEX_OP3(vpermilpd, 3, 1, 0x05, VEXF_MODRM | VEXF_IMM8, OPT_IM8, OPT_XYZMM | OPT_EA, OPT_XYZMM)

DEF_VEX_OP4(vperm2f128,  3, 1, 0x06, VEXF_MODRM | VEXF_IMM8, OPT_IM8, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP4(vinsertf128, 3, 1, 0x18, VEXF_MODRM | VEXF_IMM8, OPT_IM8, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vextractf128, 3, 1, 0x19, VEXF_MODRM | VEXF_IMM8, OPT_IM8, OPT_XYZMM, OPT_XYZMM | OPT_EA)

DEF_VEX_OP2(vbroadcastss,   2, 1, 0x18, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM)
DEF_VEX_OP2(vbroadcastsd,   2, 1, 0x19, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM)
DEF_VEX_OP2(vbroadcastf128, 2, 1, 0x1a, VEXF_MODRM, OPT_EA, OPT_XYZMM)

DEF_VEX_OP0(vzeroupper, 1, 0, 0x77, 0)
DEF_VEX_OP0(vzeroall,   1, 0, 0x77, VEXF_L256)

DEF_VEX_OP3(vroundps, 3, 1, 0x08, VEXF_MODRM | VEXF_IMM8, OPT_IM8, OPT_XYZMM | OPT_EA, OPT_XYZMM)
DEF_VEX_OP3(vroundpd, 3, 1, 0x09, VEXF_MODRM | VEXF_IMM8, OPT_IM8, OPT_XYZMM | OPT_EA, OPT_XYZMM)
DEF_VEX_OP4(vroundss, 3, 1, 0x0a, VEXF_MODRM | VEXF_IMM8, OPT_IM8, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP4(vroundsd, 3, 1, 0x0b, VEXF_MODRM | VEXF_IMM8, OPT_IM8, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)

DEF_VEX_OP4(vdpps, 3, 1, 0x40, VEXF_MODRM | VEXF_IMM8, OPT_IM8, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP4(vdppd, 3, 1, 0x41, VEXF_MODRM | VEXF_IMM8, OPT_IM8, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)

DEF_VEX_OP2(vptest, 2, 1, 0x17, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM)

/* ============================================================ */
/* Section 7: AVX2 Integer                                      */
/* ============================================================ */

DEF_VEX_OP3(vpaddb,   1, 1, 0xfc, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vpaddw,   1, 1, 0xfd, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vpaddd,   1, 1, 0xfe, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vpaddq,   1, 1, 0xd4, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vpaddsb,  1, 1, 0xec, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vpaddsw,  1, 1, 0xed, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vpaddusb, 1, 1, 0xdc, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vpaddusw, 1, 1, 0xdd, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)

DEF_VEX_OP3(vpsubb,   1, 1, 0xf8, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vpsubw,   1, 1, 0xf9, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vpsubd,   1, 1, 0xfa, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vpsubq,   1, 1, 0xfb, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vpsubsb,  1, 1, 0xe8, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vpsubsw,  1, 1, 0xe9, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vpsubusb, 1, 1, 0xd8, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vpsubusw, 1, 1, 0xd9, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)

DEF_VEX_OP3(vpmullw,  1, 1, 0xd5, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vpmulhw,  1, 1, 0xe5, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vpmulhuw, 1, 1, 0xe4, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vpmulld,  2, 1, 0x40, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vpmuldq,  2, 1, 0x28, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vpmuludq, 1, 1, 0xf4, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vpmaddwd, 1, 1, 0xf5, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)

DEF_VEX_OP3(vpand,    1, 1, 0xdb, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vpandn,   1, 1, 0xdf, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vpor,     1, 1, 0xeb, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vpxor,    1, 1, 0xef, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)

DEF_VEX_OP3(vpcmpeqb, 1, 1, 0x74, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vpcmpeqw, 1, 1, 0x75, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vpcmpeqd, 1, 1, 0x76, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vpcmpeqq, 2, 1, 0x29, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vpcmpgtb, 1, 1, 0x64, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vpcmpgtw, 1, 1, 0x65, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vpcmpgtd, 1, 1, 0x66, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vpcmpgtq, 2, 1, 0x37, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)

DEF_VEX_OP3(vpminub,  1, 1, 0xda, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vpminuw,  2, 1, 0x3a, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vpminsb,  2, 1, 0x38, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vpminsw,  1, 1, 0xea, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vpminsd,  2, 1, 0x39, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vpmaxub,  1, 1, 0xde, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vpmaxuw,  2, 1, 0x3e, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vpmaxsb,  2, 1, 0x3c, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vpmaxsw,  1, 1, 0xee, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vpmaxsd,  2, 1, 0x3d, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)

DEF_VEX_OP2(vpabsb,   2, 1, 0x1c, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM)
DEF_VEX_OP2(vpabsw,   2, 1, 0x1d, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM)
DEF_VEX_OP2(vpabsd,   2, 1, 0x1e, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM)

DEF_VEX_OP3(vpsllw,   1, 1, 0xf1, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vpslld,   1, 1, 0xf2, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vpsllq,   1, 1, 0xf3, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vpsrlw,   1, 1, 0xd1, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vpsrld,   1, 1, 0xd2, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vpsrlq,   1, 1, 0xd3, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vpsraw,   1, 1, 0xe1, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vpsrad,   1, 1, 0xe2, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)

DEF_VEX_OP3(vpunpcklbw,  1, 1, 0x60, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vpunpcklwd,  1, 1, 0x61, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vpunpckldq,  1, 1, 0x62, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vpunpcklqdq, 1, 1, 0x6c, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vpunpckhbw,  1, 1, 0x68, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vpunpckhwd,  1, 1, 0x69, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vpunpckhdq,  1, 1, 0x6a, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vpunpckhqdq, 1, 1, 0x6d, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)

DEF_VEX_OP3(vpacksswb, 1, 1, 0x63, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vpackssdw, 1, 1, 0x6b, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vpackuswb, 1, 1, 0x67, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vpackusdw, 2, 1, 0x2b, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)

DEF_VEX_OP3(vpshufb,   2, 1, 0x00, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vpshufd,   1, 1, 0x70, VEXF_MODRM | VEXF_IMM8, OPT_IM8, OPT_XYZMM | OPT_EA, OPT_XYZMM)
DEF_VEX_OP3(vpshufhw,  1, 2, 0x70, VEXF_MODRM | VEXF_IMM8, OPT_IM8, OPT_XYZMM | OPT_EA, OPT_XYZMM)
DEF_VEX_OP3(vpshuflw,  1, 3, 0x70, VEXF_MODRM | VEXF_IMM8, OPT_IM8, OPT_XYZMM | OPT_EA, OPT_XYZMM)

DEF_VEX_OP4(vpblendw,  3, 1, 0x0e, VEXF_MODRM | VEXF_IMM8, OPT_IM8, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP4(vpblendd,  3, 1, 0x02, VEXF_MODRM | VEXF_IMM8, OPT_IM8, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)

DEF_VEX_OP2(vpbroadcastb, 2, 1, 0x78, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM)
DEF_VEX_OP2(vpbroadcastw, 2, 1, 0x79, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM)
DEF_VEX_OP2(vpbroadcastd, 2, 1, 0x58, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM)
DEF_VEX_OP2(vpbroadcastq, 2, 1, 0x59, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM)

DEF_VEX_OP3(vpermd,       2, 1, 0x36, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vpermq,       3, 1, 0x00, VEXF_MODRM | VEXF_IMM8 | VEXF_W1, OPT_IM8, OPT_XYZMM | OPT_EA, OPT_XYZMM)
DEF_VEX_OP4(vinserti128,  3, 1, 0x38, VEXF_MODRM | VEXF_IMM8, OPT_IM8, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vextracti128, 3, 1, 0x39, VEXF_MODRM | VEXF_IMM8, OPT_IM8, OPT_XYZMM, OPT_XYZMM | OPT_EA)
DEF_VEX_OP4(vperm2i128,   3, 1, 0x46, VEXF_MODRM | VEXF_IMM8, OPT_IM8, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)

DEF_VEX_OP2(vmovntdqa, 2, 1, 0x2a, VEXF_MODRM, OPT_EA, OPT_XYZMM)

/* ============================================================ */
/* Section 8: FMA3 (mm=2: 0F38, pp=1: 66)                       */
/* ============================================================ */

/* vfmadd132: dst = dst * src2 + src1 */
DEF_VEX_OP3(vfmadd132ps, 2, 1, 0x98, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vfmadd132pd, 2, 1, 0x98, VEXF_MODRM | VEXF_W1, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vfmadd132ss, 2, 1, 0x99, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vfmadd132sd, 2, 1, 0x99, VEXF_MODRM | VEXF_W1, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)

/* vfmadd213: dst = src1 * dst + src2 */
DEF_VEX_OP3(vfmadd213ps, 2, 1, 0xa8, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vfmadd213pd, 2, 1, 0xa8, VEXF_MODRM | VEXF_W1, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vfmadd213ss, 2, 1, 0xa9, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vfmadd213sd, 2, 1, 0xa9, VEXF_MODRM | VEXF_W1, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)

/* vfmadd231: dst = src1 * src2 + dst */
DEF_VEX_OP3(vfmadd231ps, 2, 1, 0xb8, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vfmadd231pd, 2, 1, 0xb8, VEXF_MODRM | VEXF_W1, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vfmadd231ss, 2, 1, 0xb9, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vfmadd231sd, 2, 1, 0xb9, VEXF_MODRM | VEXF_W1, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)

/* vfmsub132: dst = dst * src2 - src1 */
DEF_VEX_OP3(vfmsub132ps, 2, 1, 0x9a, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vfmsub132pd, 2, 1, 0x9a, VEXF_MODRM | VEXF_W1, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vfmsub132ss, 2, 1, 0x9b, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vfmsub132sd, 2, 1, 0x9b, VEXF_MODRM | VEXF_W1, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)

/* vfmsub213 */
DEF_VEX_OP3(vfmsub213ps, 2, 1, 0xaa, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vfmsub213pd, 2, 1, 0xaa, VEXF_MODRM | VEXF_W1, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vfmsub213ss, 2, 1, 0xab, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vfmsub213sd, 2, 1, 0xab, VEXF_MODRM | VEXF_W1, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)

/* vfmsub231 */
DEF_VEX_OP3(vfmsub231ps, 2, 1, 0xba, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vfmsub231pd, 2, 1, 0xba, VEXF_MODRM | VEXF_W1, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vfmsub231ss, 2, 1, 0xbb, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vfmsub231sd, 2, 1, 0xbb, VEXF_MODRM | VEXF_W1, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)

/* vfnmadd132: dst = -(dst * src2) + src1 */
DEF_VEX_OP3(vfnmadd132ps, 2, 1, 0x9c, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vfnmadd132pd, 2, 1, 0x9c, VEXF_MODRM | VEXF_W1, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vfnmadd132ss, 2, 1, 0x9d, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vfnmadd132sd, 2, 1, 0x9d, VEXF_MODRM | VEXF_W1, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)

/* vfnmadd213 */
DEF_VEX_OP3(vfnmadd213ps, 2, 1, 0xac, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vfnmadd213pd, 2, 1, 0xac, VEXF_MODRM | VEXF_W1, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vfnmadd213ss, 2, 1, 0xad, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vfnmadd213sd, 2, 1, 0xad, VEXF_MODRM | VEXF_W1, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)

/* vfnmadd231 */
DEF_VEX_OP3(vfnmadd231ps, 2, 1, 0xbc, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vfnmadd231pd, 2, 1, 0xbc, VEXF_MODRM | VEXF_W1, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vfnmadd231ss, 2, 1, 0xbd, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vfnmadd231sd, 2, 1, 0xbd, VEXF_MODRM | VEXF_W1, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)

/* vfnmsub132: dst = -(dst * src2) - src1 */
DEF_VEX_OP3(vfnmsub132ps, 2, 1, 0x9e, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vfnmsub132pd, 2, 1, 0x9e, VEXF_MODRM | VEXF_W1, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vfnmsub132ss, 2, 1, 0x9f, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vfnmsub132sd, 2, 1, 0x9f, VEXF_MODRM | VEXF_W1, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)

/* vfnmsub213 */
DEF_VEX_OP3(vfnmsub213ps, 2, 1, 0xae, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vfnmsub213pd, 2, 1, 0xae, VEXF_MODRM | VEXF_W1, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vfnmsub213ss, 2, 1, 0xaf, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vfnmsub213sd, 2, 1, 0xaf, VEXF_MODRM | VEXF_W1, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)

/* vfnmsub231 */
DEF_VEX_OP3(vfnmsub231ps, 2, 1, 0xbe, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vfnmsub231pd, 2, 1, 0xbe, VEXF_MODRM | VEXF_W1, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vfnmsub231ss, 2, 1, 0xbf, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vfnmsub231sd, 2, 1, 0xbf, VEXF_MODRM | VEXF_W1, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)

/* vfmaddsub132 / 213 / 231 */
DEF_VEX_OP3(vfmaddsub132ps, 2, 1, 0x96, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vfmaddsub132pd, 2, 1, 0x96, VEXF_MODRM | VEXF_W1, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vfmaddsub213ps, 2, 1, 0xa6, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vfmaddsub213pd, 2, 1, 0xa6, VEXF_MODRM | VEXF_W1, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vfmaddsub231ps, 2, 1, 0xb6, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vfmaddsub231pd, 2, 1, 0xb6, VEXF_MODRM | VEXF_W1, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)

/* vfmsubadd132 / 213 / 231 */
DEF_VEX_OP3(vfmsubadd132ps, 2, 1, 0x97, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vfmsubadd132pd, 2, 1, 0x97, VEXF_MODRM | VEXF_W1, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vfmsubadd213ps, 2, 1, 0xa7, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vfmsubadd213pd, 2, 1, 0xa7, VEXF_MODRM | VEXF_W1, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vfmsubadd231ps, 2, 1, 0xb7, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vfmsubadd231pd, 2, 1, 0xb7, VEXF_MODRM | VEXF_W1, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)

/* ============================================================ */
/* Section 9: AES-NI & PCLMULQDQ VEX forms                      */
/* ============================================================ */

DEF_VEX_OP3(vaesenc,        2, 1, 0xdc, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vaesenclast,    2, 1, 0xdd, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vaesdec,        2, 1, 0xde, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vaesdeclast,    2, 1, 0xdf, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP2(vaesimc,        2, 1, 0xdb, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM)
DEF_VEX_OP3(vaeskeygenassist, 3, 1, 0xdf, VEXF_MODRM | VEXF_IMM8, OPT_IM8, OPT_XYZMM | OPT_EA, OPT_XYZMM)
DEF_VEX_OP4(vpclmulqdq,     3, 1, 0x44, VEXF_MODRM | VEXF_IMM8, OPT_IM8, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)

/* ============================================================ */
/* Section 10: SHA-NI                                           */
/* ============================================================ */

DEF_VEX_OP3(sha1rnds4,   3, 0, 0xcc, VEXF_MODRM | VEXF_IMM8, OPT_IM8, OPT_XYZMM | OPT_EA, OPT_XYZMM)
DEF_VEX_OP2(sha1nexte,   2, 0, 0xc8, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM)
DEF_VEX_OP2(sha1msg1,    2, 0, 0xc9, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM)
DEF_VEX_OP2(sha1msg2,    2, 0, 0xca, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM)
DEF_VEX_OP3(sha256rnds2, 2, 0, 0xcb, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP2(sha256msg1,  2, 0, 0xcc, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM)
DEF_VEX_OP2(sha256msg2,  2, 0, 0xcd, VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM)

/* ============================================================ */
/* Section 11: AVX-512F Core (EVEX-specific instructions)       */
/* ============================================================ */

DEF_VEX_OP4(vrangeps,    3, 1, 0x50, VEXF_EVEX | VEXF_MODRM | VEXF_IMM8, OPT_IM8, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP4(vrangepd,    3, 1, 0x50, VEXF_EVEX | VEXF_MODRM | VEXF_IMM8 | VEXF_W1, OPT_IM8, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP4(vreduceps,   3, 1, 0x56, VEXF_EVEX | VEXF_MODRM | VEXF_IMM8, OPT_IM8, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP4(vreducepd,   3, 1, 0x56, VEXF_EVEX | VEXF_MODRM | VEXF_IMM8 | VEXF_W1, OPT_IM8, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP4(vrndscaleps, 3, 1, 0x08, VEXF_EVEX | VEXF_MODRM | VEXF_IMM8, OPT_IM8, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP4(vrndscalepd, 3, 1, 0x09, VEXF_EVEX | VEXF_MODRM | VEXF_IMM8 | VEXF_W1, OPT_IM8, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vscalefps,   2, 1, 0x2c, VEXF_EVEX | VEXF_MODRM, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP3(vscalefpd,   2, 1, 0x2c, VEXF_EVEX | VEXF_MODRM | VEXF_W1, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP4(vpternlogd,  3, 1, 0x25, VEXF_EVEX | VEXF_MODRM | VEXF_IMM8, OPT_IM8, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)
DEF_VEX_OP4(vpternlogq,  3, 1, 0x25, VEXF_EVEX | VEXF_MODRM | VEXF_IMM8 | VEXF_W1, OPT_IM8, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_XYZMM)

DEF_VEX_OP4(vpcmpb, 3, 1, 0x3f, VEXF_EVEX | VEXF_MODRM | VEXF_IMM8, OPT_IM8, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_MASK)
DEF_VEX_OP4(vpcmpw, 3, 1, 0x3f, VEXF_EVEX | VEXF_MODRM | VEXF_IMM8 | VEXF_W1, OPT_IM8, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_MASK)
DEF_VEX_OP4(vpcmpd, 3, 1, 0x1f, VEXF_EVEX | VEXF_MODRM | VEXF_IMM8, OPT_IM8, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_MASK)
DEF_VEX_OP4(vpcmpq, 3, 1, 0x1f, VEXF_EVEX | VEXF_MODRM | VEXF_IMM8 | VEXF_W1, OPT_IM8, OPT_XYZMM | OPT_EA, OPT_XYZMM, OPT_MASK)
